# Generated by Django 5.1.6 on 2025-02-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students_models",
            name="students_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="students_models",
            name="students_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="students_models",
            name="students_is_available",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="students_models",
            name="students_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="students_models",
            name="students_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
