# Generated by Django 5.1.6 on 2025-02-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffs_models",
            name="staffs_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffs_models",
            name="staffs_descriptions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="staffs_models",
            name="staffs_is_available",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="staffs_models",
            name="staffs_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="staffs_models",
            name="staffs_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
