# Generated by Django 5.1.6 on 2025-02-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructor_models",
            old_name="Name",
            new_name="instructore_name",
        ),
    ]
