# Generated by Django 5.1.6 on 2025-02-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0002_rename_name_instructor_models_instructore_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="instructor_models", new_name="instructors_models",
        ),
        migrations.RenameField(
            model_name="instructors_models",
            old_name="instructore_name",
            new_name="instructors_name",
        ),
    ]
