# Generated by Django 5.1.6 on 2025-02-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0003_rename_instructor_models_instructors_models_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructors_models",
            name="instructors_descriptions",
            field=models.TextField(blank=True),
        ),
    ]
