# Generated by Django 5.1.6 on 2025-02-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0004_instructors_models_instructors_descriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructors_models",
            name="instructors_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instructors_models",
            name="instructors_is_available",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="instructors_models",
            name="instructors_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="instructors_models",
            name="instructors_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
