# Generated by Django 5.1.6 on 2025-02-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="boards_models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boards_name", models.CharField(blank=True, max_length=100)),
                ("boards_description", models.TextField(blank=True)),
                ("boards_age", models.IntegerField(blank=True, null=True)),
                (
                    "boards_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("boards_rating", models.FloatField(blank=True, null=True)),
                (
                    "boards_is_available",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
            ],
        ),
    ]
